In [6]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.0


In [5]:
t1 = tf.Variable([1, 2, 3])
t2 = tf.constant([1, 2, 3])

print(t1)
print(t2)

print("=========")

print(type(t1))
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>



### Variable
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>

### constant
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

<class 'tensorflow.python.framework.ops.EagerTensor'>


Variable은 변화하는 값이기 때문에 가중치나 편향 값에 사용

Constant는 불변성을 가지기 때문에 데이터셋에 있는 값에 사용

In [7]:
test_list = [1, 2, 3]
test_np = np.array([1, 2, 3])

t1 = tf.constant(test_list)
t2 = tf.constant(test_np)

print(t1)
print(t2)

print("=========")

print(type(t1))
print(type(t2))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int64)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [13]:
t1 = tf.constant(test_list)
t2 = tf.Variable(test_list)

# 상수 -> 변수 형변환은 되지만 변수 -> 상수 형변환 X
# t3 = tf.constant(t2)
t4 = tf.Variable(t1)

print(t4)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [14]:
t1 = tf.convert_to_tensor(test_list)
t2 = tf.convert_to_tensor(test_np)

print(type(t1))
print(type(t2))

print("=================")

t3 = tf.Variable(test_list)
# convert_to_tensor를 통해 변수 -> 상수 형변환을 해줄 수 있음
t4 = tf.convert_to_tensor(t3)

print(type(t3))
print(type(t4))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [16]:
test_list1 = [10, 20, 30]
test_list2 = [1, 2, 3]

t1 = tf.constant(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
print(type(t3)) # constant타입이 나온다

t1 = tf.Variable(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
print(type(t3)) # constant타입이 나온다

print(dir(t1)) # 내부 메서드 확인

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
['SaveSliceInfo', '_OverloadAllOperators', '_OverloadOperator', '_TensorConversionFunction', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__bool__', '__class__', '__complex__', '__copy__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__idiv__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ipow__', '__irealdiv__', '__isub__', '__iter__', '__itruediv__', '__le__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rsub__', '