In [3]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np

print(tf.__version__)

2.8.0


In [ ]:
# 데이터 분류는 학습과 연관되지 않은 데이터를 검증, 테스트용에 사용해야한다. (Wild한 상황을 반영해야하기 때문)
train_x = np.arange(100).reshape(-1, 1)
train_y = 3 * train_x + 1

train_validation_ds = tf.data.Dataset.from_tensor_slices((train_x, train_y))

n_train_validation = 100
train_ratio = 0.8
n_train = int(n_train_validation * train_ratio)

train_ds = train_validation_ds.take(n_train) # 전체 데이터에서 80%만큼 학습데이터로 지정


In [9]:
train_x = np.arange(100).reshape(-1, 1)
train_y = 3 * train_x + 1

train_validation_ds = tf.data.Dataset.from_tensor_slices((train_x, train_y))

n_train_validation = 100 # 데이터의 전체개수와
train_ratio = 0.8 # 얼마만큼 나눌 것인지의 비율을 알아야 나눌 수 있다.
n_train = int(n_train_validation * train_ratio)
n_validation = n_train_validation - n_train

remaining_ds = train_validation_ds.skip(n_train) 
validation_ds = remaining_ds.take(n_validation)

for x, y in validation_ds:
    print(x, y)

tf.Tensor([80], shape=(1,), dtype=int64) tf.Tensor([241], shape=(1,), dtype=int64)
tf.Tensor([81], shape=(1,), dtype=int64) tf.Tensor([244], shape=(1,), dtype=int64)
tf.Tensor([82], shape=(1,), dtype=int64) tf.Tensor([247], shape=(1,), dtype=int64)
tf.Tensor([83], shape=(1,), dtype=int64) tf.Tensor([250], shape=(1,), dtype=int64)
tf.Tensor([84], shape=(1,), dtype=int64) tf.Tensor([253], shape=(1,), dtype=int64)
tf.Tensor([85], shape=(1,), dtype=int64) tf.Tensor([256], shape=(1,), dtype=int64)
tf.Tensor([86], shape=(1,), dtype=int64) tf.Tensor([259], shape=(1,), dtype=int64)
tf.Tensor([87], shape=(1,), dtype=int64) tf.Tensor([262], shape=(1,), dtype=int64)
tf.Tensor([88], shape=(1,), dtype=int64) tf.Tensor([265], shape=(1,), dtype=int64)
tf.Tensor([89], shape=(1,), dtype=int64) tf.Tensor([268], shape=(1,), dtype=int64)
tf.Tensor([90], shape=(1,), dtype=int64) tf.Tensor([271], shape=(1,), dtype=int64)
tf.Tensor([91], shape=(1,), dtype=int64) tf.Tensor([274], shape=(1,), dtype=int64)
tf.T

In [23]:
(train_validation_ds, test_ds), ds_info = tfds.load(name='mnist',
                                                    shuffle_files=True,
                                                    as_supervised=True,
                                                    with_info=True,
                                                    split=['train', 'test'])

n_train_validation = ds_info.splits['train'].num_examples
train_ratio = 0.8
n_train = int(n_train_validation * train_ratio)
n_validation = n_train_validation - n_train

train_ds = remaining_ds.take(n_train)
remaining_ds = train_validation_ds.skip(n_train)
validation_ds = remaining_ds.take(n_validation)

train_ds = train_ds.shuffle(100).batch(32)
validation_ds = validation_ds.batch(32)
test_ds = test_ds.batch(32)