In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.8.0


In [6]:
# tensor의 연산
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([10, 20, 30])

print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)
print(t1 // t2)

t1 = [1, 2, 3]
t2 = [10, 20, 30]

print(t1 + t2)
# print(t1 - t2) 에러
# print(t1 * t2) 에러
# print(t1 / t2) 에러
# print(t1 // t2) 에러

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
tf.Tensor([ -9 -18 -27], shape=(3,), dtype=int32)
tf.Tensor([10 40 90], shape=(3,), dtype=int32)
tf.Tensor([0.1 0.1 0.1], shape=(3,), dtype=float64)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
[1, 2, 3, 10, 20, 30]


In [14]:
# 데이터 타입 변환하기
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t2 = tf.random.normal(shape=(3, 1), mean=0, stddev=5) # 행이 안맞을 경우 기존 행을 확장한다., 단 변경할 수 없는 구조이면 에러 발생

t1 = tf.cast(t1, dtype=tf.int16)
t2 = tf.cast(t2, dtype=tf.int16)

t3 = t1 + t2

print(t1.numpy(), '\n') # numpy로 변경하면 더 깔끔하게 볼 수 있다
print(t2.numpy(), '\n')
print(t3.numpy(), '\n')

[[-5 -7  3 -3]
 [ 0 12 -4  0]
 [ 0  2 -1 -4]] 

[[-5]
 [-3]
 [-6]] 

[[-10 -12  -2  -8]
 [ -3   9  -7  -3]
 [ -6  -4  -7 -10]] 



In [33]:
# 셀을 조작함수
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)

# tf.reduce_sum -> 합
# tf.reduce_prod -> 곱

# tf.reduce_max -> (축 내에서) 최대
# tf.reduce_min -> 최소

# tf.reduce_mean -> 평균
# tf.reduce_std -> 표준 편차
# tf.reduce_variance -> 분산(float타입)

# tf.reduce_all -> 논리연산 AND
# tf.reduce_any -> 논리연산 OR

t2 = tf.reduce_sum(t1)
print(t1.numpy())
print(t2.numpy(), '\n')

#특정 축을 기준으로 합을 구하고 싶을 때 
# axis = 0 -> 세로축, axis = 1 -> 가로축을 의미하고 reduce_sum에 넣는다는 것은 해당 축에 대한 합을 구하겠다는 것
t2 = tf.reduce_max(t1, axis=1)
print(t1.numpy())
print(t2.numpy())


[[ 0  2 -2 -2]
 [ 3  7 -3  4]
 [ 1 -3 -9 -3]]
-5 

[[ 0  2 -2 -2]
 [ 3  7 -3  4]
 [ 1 -3 -9 -3]]
[2 7 1]
