In [4]:
import tensorflow as tf
import pandas as pd
print(tf.__version__)

2.8.0


In [6]:
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)
encoding = pd.get_dummies(iris)

print(type(encoding))

<class 'pandas.core.frame.DataFrame'>


In [18]:
x_train = tf.constant(encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']])
y_train = tf.constant(encoding[['품종_setosa', '품종_versicolor', '품종_virginica']])

print(x_train.shape, y_train.shape)

(150, 4) (150, 3)


In [19]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(3, activation='softmax', input_shape=(4, )))

model.compile(loss='categorical_crossentropy', optimizer='sgd')

In [20]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 6ms/step - loss: 2.7045
Epoch 2/100
5/5 [==============================] - 0s 5ms/step - loss: 1.3837
Epoch 3/100
5/5 [==============================] - 0s 7ms/step - loss: 0.9499
Epoch 4/100
5/5 [==============================] - 0s 5ms/step - loss: 0.7561
Epoch 5/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6568
Epoch 6/100
1/5 [=====>........................] - ETA: 0s - loss: 0.6165

2022-05-11 02:02:51.173210: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


5/5 [==============================] - 0s 5ms/step - loss: 0.6026
Epoch 7/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5788
Epoch 8/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5645
Epoch 9/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5550
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 0.5491
Epoch 11/100
5/5 [==============================] - 0s 4ms/step - loss: 0.5392
Epoch 12/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5308
Epoch 13/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5236
Epoch 14/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5179
Epoch 15/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5107
Epoch 16/100
5/5 [==============================] - 0s 5ms/step - loss: 0.5055
Epoch 17/100
5/5 [==============================] - 0s 5ms/step - loss: 0.4994
Epoch 18/100
5/5 [==============================] - 0s 5ms/step - lo

In [21]:

print(f"result: {y_train[0:5]}")

print(f"expect: {model.predict(x_train[0:5])}")

result: [[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
expect: [[9.0413630e-01 9.4929941e-02 9.3378790e-04]
 [8.3656436e-01 1.6055048e-01 2.8851305e-03]
 [8.8425881e-01 1.1402830e-01 1.7128513e-03]
 [8.4633225e-01 1.5072846e-01 2.9393397e-03]
 [9.1607684e-01 8.3153516e-02 7.6962489e-04]]


2022-05-11 02:02:55.365923: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
